wbt_car: 0.1
camera:
  front: 1
  side: 2
io:
  left_sensor: 1
  right_sensor: 6
  key: 2
  light: 7
speed:
  x:
    limit: 0.7
  y:
    limit: 0.7
  angle:
    limit: 3

# 巡航pid
lane_pid:
  cfg_pid_y:
    Kp: 5
    Ki: 0
    Kd: 0
    setpoint: 0
    output_limits: [-0.7, 0.7]
  cfg_pid_angle:
    Kp: 3
    Ki: 0
    Kd: 0
    setpoint: 0
    output_limits: [-1.5, 1.5]
# det巡航pid
det_pid:
  cfg_pid_y:
    Kp: 0.3
    Ki: 0
    Kd: 0.005
    setpoint: 0
    output_limits: [-0.7, 0.7]
  cfg_pid_angle:
    Kp: 1.2
    Ki: 0
    Kd: 0.005
    setpoint: 0
    output_limits: [-1.5, 1.5]

# 定位pid参数
location_pid:
  pid_x:
    Kp: 0.5
    Ki: 0
    Kd: 0.005
    setpoint: 0
    output_limits: [-0.7, 0.7]
  pid_y:
    Kp: 1.2
    Ki: 0
    Kd: 0.005
    setpoint: 0
    output_limits: [-1.5, 1.5]